Name:           ros-jade-hector-object-tracker
Version:        0.3.3
Release:        0%{?dist}
Summary:        ROS hector_object_tracker package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/hector_object_tracker
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-hector-marker-drawing
Requires:       ros-jade-hector-nav-msgs
Requires:       ros-jade-hector-worldmodel-msgs
Requires:       ros-jade-image-geometry
Requires:       ros-jade-roscpp
Requires:       ros-jade-tf
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-cmake-modules
BuildRequires:  ros-jade-hector-marker-drawing
BuildRequires:  ros-jade-hector-nav-msgs
BuildRequires:  ros-jade-hector-worldmodel-msgs
BuildRequires:  ros-jade-image-geometry
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-tf

%description
hector_object_tracker is the core package of hector_worldmodel. It listens to
percept message from detectors (e.g. heat signatures of persons or recognitions
of other objects of interest in the scene) and fuses all information to a single
worldmodel state. Objects will be tracked over time and their states can be
influenced by a couple of services. The percept to object association problem is
solved either automatically based on the Mahalanobis distance, or a unique
object_id can be given in the percept message. If a
hector_nav_msgs/GetDistanceToObstacle service is available, the object_tracker
can optionally deduce the depth of objects in the scene by projection to the
nearest obstacle (wall).

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Tue Nov 10 2015 Johannes Meyer <meyer@fsr.tu-darmstadt.de> - 0.3.3-0
- Autogenerated by Bloom

