Name:           ros-kinetic-hector-object-tracker
Version:        0.3.4
Release:        0%{?dist}
Summary:        ROS hector_object_tracker package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/hector_object_tracker
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-hector-marker-drawing
Requires:       ros-kinetic-hector-nav-msgs
Requires:       ros-kinetic-hector-worldmodel-msgs
Requires:       ros-kinetic-image-geometry
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-tf
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-hector-marker-drawing
BuildRequires:  ros-kinetic-hector-nav-msgs
BuildRequires:  ros-kinetic-hector-worldmodel-msgs
BuildRequires:  ros-kinetic-image-geometry
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-tf

%description
hector_object_tracker is the core package of hector_worldmodel. It listens to
percept message from detectors (e.g. heat signatures of persons or recognitions
of other objects of interest in the scene) and fuses all information to a single
worldmodel state. Objects will be tracked over time and their states can be
influenced by a couple of services. The percept to object association problem is
solved either automatically based on the Mahalanobis distance, or a unique
object_id can be given in the percept message. If a
hector_nav_msgs/GetDistanceToObstacle service is available, the object_tracker
can optionally deduce the depth of objects in the scene by projection to the
nearest obstacle (wall).

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Fri Jun 24 2016 Johannes Meyer <meyer@fsr.tu-darmstadt.de> - 0.3.4-0
- Autogenerated by Bloom

